/* Program Name: DDeFrayne_HW09_prog											   */
/* Program Location: C:\Users\defraydz\Documents\School Work					   */
/* Creation Date: 3/4/2019 													       */
/* Author: Don DeFrayne 														   */
/* Purpose: Work with SAS Macros												   */
/* Inputs: N/A																	   */
/* Outputs: DDeFrayne_HW09_output.pdf 											   */
/***********************************************************************************/

*2 Define hwnum for the output;
%let hwnum = 09;

*Library definitions;
libname hwref 'C:\Users\defraydz\Documents\School Work\SAS\HWREF' access=readonly;
libname orion 'C:\Users\defraydz\Documents\School Work\SAS\Data';
libname myhw 'C:\Users\defraydz\Documents\School Work\SAS\MYHW';
filename hw "C:\Users\defraydz\Documents\School Work\SAS\%NRSTR(A&M)\DDeFrayne_HW&hwnum._output.pdf";

*1 Write macro variable values to the log as they are resolved;
options symbolgen;

*1 Write the text generated by macro execution to the log;
options mprint;

*1 Do not display date or time;
options nodate nonumber;

*PDF output;
ods pdf file=hw;

*3 Copy ncaam2006 into work library and change School to Team;
data ncaam2006;
	set hwref.ncaam2006(rename=(School=Team));
	label Team = 'Team';
run;

*4 Rewrite Assignment 6's SQL code as a macro;
%macro teamcalla;
	proc sql;
	title "Number of Players per Team in %substr(&file,6,4) Data";
	SELECT Team, COUNT(Player)
		FROM &lib..&file /*Use &lib for the library, and &file for the data set*/
		GROUP BY Team;
	quit;
	title;
%mend teamcalla;

*5 Create the two macro variables for %teamcall, &lib and &file;
%let lib = hwref;
%let file = ncaam2003;

*6 Call the teamcall macro;
%teamcalla;

*7 Change the value of &file to reference ncaam2004, and call the teamcall macro again;
%let file = ncaam2004;
%teamcalla;

*8 Modify the macro so that it uses a positional parameter for the filename and a keyword for the playermin;
%macro teamcallb(fullname,playermin=1);
	proc sql;
	title "Number of Players per Team in %substr(&fullname,%sysfunc(length(&fullname))-3) Data";
	title2 "Teams with at Least &playermin Players in the Data Set";
	SELECT Team, COUNT(Player)
		FROM &fullname /*Use &lib for the library, and &file for the data set*/
		GROUP BY Team
		HAVING COUNT(Player) >= &playermin;
	quit;
	title;
%mend teamcallb;

*9 Call the macro for ncaam2004;
%teamcallb(hwref.ncaam2004);

*10 Call the macro for ncaam2006 with a minimum player base of 5;
%teamcallb(ncaam2006, playermin=5);

*11 Modify the macro by adding a footnote and saving it;
options mstored sasmstore=myhw;

%macro teamcallc(fullname,playermin=1) / store source;
	%let dt = %sysfunc(date(),mmddyy10.);
	%let tm = %sysfunc(time(),timeampm8.);
	proc sql;
	title "Number of Players per Team in %substr(&fullname,%sysfunc(length(&fullname))-3) Data";
	title2 "Teams with at Least &playermin Players in the Data Set";
	footnote "Produced by a Stored Compiled Macro at &tm on &dt";

	SELECT Team, COUNT(Player)
		FROM &fullname /*Use &lib for the library, and &file for the data set*/
		GROUP BY Team
		HAVING COUNT(Player) >= &playermin;
	quit;
	title;
	footnote;
%mend teamcallc;

*12 Call teamcallc for ncaam2003;
%teamcallc(hwref.ncaam2003);

*13 List all user-defined macros permanently stored in myhw;
title 'Compiled Macros in My Permanent Library';
proc catalog cat=myhw.sasmacr;
	contents;
quit;

*Close the pdf output;
ods pdf close;
